# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: mycomputeragent

jobs:
  - job: sql
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      name: sqlJob
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'ARMPipeline-conn'
        subscriptionId: '8b5c630a-aae6-468d-98df-47551225b49a'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'armgr4'
        location: 'West Europe'
        templateLocation: 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/Jovan992/TaskTracker/master/deployment/web-api-sql/web-api-sql-deployment.json'
        csmParametersFileLink: 'https://raw.githubusercontent.com/Jovan992/TaskTracker/master/deployment/web-api-sql/web-api-sql-deployment-parameters.json'
        overrideParameters: '-sqlAdministratorLogin $(VAR_MYSQL_USER) -sqlAdministratorLoginPassword $(VAR_MYSQL_PASS) -databaseName newdatabase'
        deploymentMode: 'Incremental'
        deploymentName: 'sqldep2'
        deploymentOutputs: sql_arm

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $armOutputObj = $env:sql_arm | convertfrom-json
          $sqlOutputObj.PSObject.Properties | ForEach-Object {
            $keyName = $_.Name
            $value = $_.Value.value
            Write-Output "##vso[task.setvariable variable=$keyName;]$value"
          }

  - job: keyVault
    dependsOn: sql
    variables:
      connectionStringOutput: $[ dependencies.sql.outputs['sqlJob.connectionString'] ]
      connectionStringOutput1: "asdasdasdasdasd"
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'ARMPipeline-conn'
        subscriptionId: '8b5c630a-aae6-468d-98df-47551225b49a'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'armgr4'
        location: 'West Europe'
        templateLocation: 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/Jovan992/TaskTracker/master/deployment/key-vault/key-vault-deployment.json'
        csmParametersFileLink: 'https://raw.githubusercontent.com/Jovan992/TaskTracker/master/deployment/key-vault/key-vault-deploment-parameters.json'
        overrideParameters: '-objectId  $(aad_objectid) -secretName SQLConnectionString -secretValue $(connectionString)'
        deploymentMode: 'Incremental'
        deploymentName: 'kvdep2'
    