# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: mycomputeragent


jobs:
  - job: sqlJob
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      name: sqlStep
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'ARMPipeline-conn'
        subscriptionId: '8b5c630a-aae6-468d-98df-47551225b49a'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'armgr4'
        location: 'West Europe'
        templateLocation: 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/Jovan992/TaskTracker/master/deployment/web-api-sql/web-api-sql-deployment.json'
        csmParametersFileLink: 'https://raw.githubusercontent.com/Jovan992/TaskTracker/master/deployment/web-api-sql/web-api-sql-deployment-parameters.json'
        overrideParameters: '-sqlAdministratorLogin $(VAR_MYSQL_USER) -sqlAdministratorLoginPassword $(VAR_MYSQL_PASS) -databaseName newdatabase'
        deploymentMode: 'Incremental'
        deploymentName: 'sqldep2'
        deploymentOutputs: sqlArm

    - task: PowerShell@2
      name: psStep
      inputs:
        targetType: 'inline'
        script: |
          $sqlArm = $env:sqlArm
          if (-not $sqlArm) {
            Write-Error "sqlArm variable not found or empty."
            exit 1
          }

          $armOutputObj = $sqlArm -split '\r?\n' | ForEach-Object {
            $keyValuePair = $_ -split ':' -replace '["{},]'
            if ($keyValuePair -ne $null -and $keyValuePair.Count -eq 2) {
              $key = $keyValuePair[0].Trim()
              $value = $keyValuePair[1].Trim()
              Write-Output "##vso[task.setvariable variable=$key;isOutput=true]$value"
            }
          }

  - job: keyVault
    dependsOn: sqlJob

    variables:
      connectionStringOutput: $[ dependencies.sqlJob.outputs['psStep.connectionString'] ]
      connectionStringOutput1: "asdasdasdasdasd"
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'ARMPipeline-conn'
        subscriptionId: '8b5c630a-aae6-468d-98df-47551225b49a'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'armgr4'
        location: 'West Europe'
        templateLocation: 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/Jovan992/TaskTracker/master/deployment/key-vault/key-vault-deployment.json'
        csmParametersFileLink: 'https://raw.githubusercontent.com/Jovan992/TaskTracker/master/deployment/key-vault/key-vault-deploment-parameters.json'
        overrideParameters: '-objectId  $(aad_objectid) -secretName SQLConnectionString -secretValue $(connectionStringOutput)'
        deploymentMode: 'Incremental'
        deploymentName: 'kvdep2'
